/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fc.splendid;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Eternity
 */
public class PlayerRecords_Guest extends javax.swing.JFrame {

    /**
     * Creates new form PlayerRecords_Guest
     */ Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        public static String jersey;
    public PlayerRecords_Guest(String J) {
        initComponents();
        this.jersey=J;
         conn=sqlconnect.connectDB();
         fetch();
    }

      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Lp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Tp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Cp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Ocp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Tg = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Ta = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(808, 616));
        setPreferredSize(new java.awt.Dimension(810, 620));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("PLAYER'S RECORDS");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(220, 10, 520, 42);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 810, 60);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("LEAGUE WON");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 120, 110, 30);

        Lp.setEditable(false);
        Lp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(Lp);
        Lp.setBounds(270, 110, 90, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("TOURNAMENTS WON");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 190, 160, 30);

        Tp.setEditable(false);
        Tp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(Tp);
        Tp.setBounds(270, 180, 90, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("CUP WON");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 250, 110, 30);

        Cp.setEditable(false);
        Cp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(Cp);
        Cp.setBounds(270, 240, 90, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("OTHER CHAMPIONSHIPS");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 310, 180, 30);

        Ocp.setEditable(false);
        Ocp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(Ocp);
        Ocp.setBounds(270, 300, 130, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("TOTAL GOAL SCORED");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 370, 180, 30);

        Tg.setEditable(false);
        Tg.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(Tg);
        Tg.setBounds(270, 360, 130, 40);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("TOTAL ASSIST");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 440, 180, 30);

        Ta.setEditable(false);
        Ta.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(Ta);
        Ta.setBounds(270, 430, 130, 40);

        jButton7.setBackground(new java.awt.Color(255, 102, 102));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(30, 530, 170, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-2, -2, 810, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
        Players_Info_Guest PIG = new Players_Info_Guest();
        PIG.setLocationRelativeTo(null);
        PIG.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */ public void fetch()
    {      
        try{
          String league="League";
          String tourney="Tourney";
          String cup="Cup";
          String other="Other";
          String goal="Goal";
          String assist="Assist";
          String sql = "select * from player_records where JerseyNo=?";
          pst = conn.prepareStatement(sql);
          pst.setString(1,jersey);
          rs = pst.executeQuery();
          if(rs.next()){
             Lp.setText(rs.getString("League"));
             
             Tp.setText(rs.getString("Tourney"));
              
             Cp.setText(rs.getString("Cup"));
             
             Ocp.setText(rs.getString("Other"));
             
             Tg.setText(rs.getString("Goal"));
             
             Ta.setText(rs.getString("Assist"));
             
             
            
          }
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(null, E);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerRecords_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerRecords_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerRecords_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerRecords_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerRecords_Guest(jersey).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cp;
    private javax.swing.JTextField Lp;
    private javax.swing.JTextField Ocp;
    private javax.swing.JTextField Ta;
    private javax.swing.JTextField Tg;
    private javax.swing.JTextField Tp;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
