/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fc.splendid;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
/**
 *
 * @author Eternity
 */
public class PlayerRecords extends javax.swing.JFrame {

    /**
     * Creates new form PlayerRecords
     */Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        ArrayList<user1> searchArray = new ArrayList<user1>();
    public PlayerRecords() {
        initComponents();
        conn=sqlconnect.connectDB();
        getUsersList();
        getUsersList1();
    }
        public ArrayList<user1> getUsersList()
   {
       String sql="select Name,JerseyNO from players_info";
       ArrayList<user1> usersList = new ArrayList<user1>();
       Statement st;    
       try {
           st = conn.createStatement();
           rs = st.executeQuery(sql);

           user1 user;

           while(rs.next())
           {
               user = new user1(rs.getString("Name"),rs.getInt("JerseyNO"));
               usersList.add(user);
           }
            Object [][]row = new Object[usersList.size()][2];
            String []name = {"Name","JerseyNo"};
            Model mo;
           for(int i = 0; i<usersList.size();i++){
           row[i][0] = usersList.get(i).getname();
           row[i][1] = usersList.get(i).getjersey();
                      
           }
            mo = new Model(row,name,2);
            jTable1.setModel(mo);
            jTable1.setRowHeight(40);
           
           TableColumn column = jTable1.getColumnModel().getColumn(2);
       } 
      catch (Exception e) {
           e.printStackTrace();
       }
       return usersList;
   }
         public ArrayList<user1> getUsersList1()
   {
       String sql="select * from player_records";
       ArrayList<user1> usersList1 = new ArrayList<user1>();
       Statement st;    
       try {
           st = conn.createStatement();
           rs = st.executeQuery(sql);

           user1 user01;

           while(rs.next())
           {
               user01 = new user1(rs.getString("Name"),rs.getInt("JerseyNo"),rs.getInt("League"),rs.getInt("Tourney"),rs.getInt("Cup"),rs.getInt("Other"),rs.getInt("Goal"),rs.getInt("Assist"));
               usersList1.add(user01);
           }
            Object [][]row = new Object[usersList1.size()][8];
            String []name = {"Name","JerseyNo","League","Tourney","Cup","Other","Goal","Assist"};
            Model mo;
           for(int i = 0; i<usersList1.size();i++){
           row[i][0] = usersList1.get(i).getname();
           row[i][1] = usersList1.get(i).getjersey();
           row[i][2] = usersList1.get(i).getleague();
           row[i][3] = usersList1.get(i).gettourney();
           row[i][4] = usersList1.get(i).getcup();
           row[i][5] = usersList1.get(i).getother();
           row[i][6] = usersList1.get(i).getgoal();
           row[i][7] = usersList1.get(i).getassist();
           
           }
            mo = new Model(row,name,8);
            jTable2.setModel(mo);
            jTable2.setRowHeight(40);
           
            jTable2.getColumnModel().getColumn(2);
       } 
      catch (Exception e) {
           e.printStackTrace();
       }
       return usersList1;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Lp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Tp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Cp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TGp = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        TAp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        OCp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JN = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        PN = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1290, 670));
        setPreferredSize(new java.awt.Dimension(1290, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel6.setBackground(new java.awt.Color(102, 0, 102));
        jPanel6.setPreferredSize(new java.awt.Dimension(1290, 650));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("LEAGUE WON");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(290, 190, 110, 30);

        Lp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel6.add(Lp);
        Lp.setBounds(520, 180, 90, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("TOURNAMENTS WON");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(290, 260, 160, 30);

        Tp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel6.add(Tp);
        Tp.setBounds(520, 250, 90, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("CUP WON");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(290, 320, 110, 30);

        Cp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel6.add(Cp);
        Cp.setBounds(520, 310, 90, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("OTHER CHAMPIONSHIPS");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(290, 380, 180, 30);

        TGp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel6.add(TGp);
        TGp.setBounds(520, 430, 90, 40);

        jButton3.setBackground(new java.awt.Color(0, 255, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);
        jButton3.setBounds(430, 580, 149, 40);

        jButton5.setBackground(new java.awt.Color(51, 51, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);
        jButton5.setBounds(600, 580, 149, 40);

        jButton6.setBackground(new java.awt.Color(255, 51, 51));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("DELETE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6);
        jButton6.setBounds(780, 580, 149, 40);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(720, 60, 550, 330);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("TOTAL GOAL SCORED");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(290, 440, 180, 30);

        TAp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel6.add(TAp);
        TAp.setBounds(520, 500, 90, 40);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("TOTAL ASSIST");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(290, 510, 180, 30);

        OCp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel6.add(OCp);
        OCp.setBounds(520, 370, 90, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("JERSEY NO");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(290, 110, 110, 30);

        JN.setEditable(false);
        JN.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel6.add(JN);
        JN.setBounds(520, 110, 90, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("NAME");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(290, 50, 110, 30);

        PN.setEditable(false);
        PN.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel6.add(PN);
        PN.setBounds(520, 50, 160, 30);

        jButton7.setBackground(new java.awt.Color(255, 102, 102));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7);
        jButton7.setBounds(20, 580, 170, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 230, 402);

        jButton8.setBackground(new java.awt.Color(204, 255, 204));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton8.setText("RESET");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8);
        jButton8.setBounds(220, 580, 170, 40);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 70, 1290, 660);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("UPDATE RECORDS");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(310, 10, 390, 42);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-2, 0, 1290, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try{
            String query="Insert into player_records (Name,JerseyNo,League,Tourney,Cup,Other,Goal,Assist) values (?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(query);

            pst.setString(1,PN.getText());
            pst.setString(2,JN.getText());
            pst.setString(3,Lp.getText());

            pst.setString(4,Tp.getText());

            pst.setString(5,Cp.getText());
            pst.setString(6,OCp.getText());
            pst.setString(7,TGp.getText());
            pst.setString(8,TAp.getText());

            if(Lp.getText().isEmpty()||Tp.getText().isEmpty()||Cp.getText().isEmpty()||OCp.getText().isEmpty()||TGp.getText().isEmpty()||TAp.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please Fill Up All the Fields");
                
                Lp.setText("");
                Tp.setText("");
                Cp.setText("");
                OCp.setText("");
                TGp.setText("");
                TAp.setText("");

            } else {
                pst.execute();
                JOptionPane.showMessageDialog(null, "Saved");

                Lp.setText("");
                Tp.setText("");
                Cp.setText("");
                OCp.setText("");
                TGp.setText("");
                TAp.setText("");

            }
        }
        catch(Exception e)
        {

            JOptionPane.showMessageDialog(null, e);
        }
        getUsersList1();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
            String value1 = PN.getText();
            String value2 = JN.getText();
            String value3 = Lp.getText();
            String value4 = Tp.getText();
            String value5 = Cp.getText();
            String value6 = OCp.getText();
            String value7 = TGp.getText();
            String value8 = TAp.getText();
            
            String sql= "update player_records set Name='"+value1+"',JerseyNo='"+value2+"',League='"+value3+"',Tourney='"+value4+"',Cup='"+value5+"',Other='"+value6+"',Goal='"+value7+"',Assist='"+value8+" ' where JerseyNo=' " +value2+" ' ";
            pst=conn.prepareStatement(sql);
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "UPDATED");
            
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(null,E);
        }
        getUsersList1();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{    
            
            pst=conn.prepareStatement("DELETE FROM player_records where JerseyNo=?");
            pst.setString(1,JN.getText());
            pst.executeUpdate();
             
            JOptionPane.showMessageDialog(null, "DELETED");
             getUsersList();
           
    }                                        
        catch(Exception E){
         JOptionPane.showMessageDialog(null,E);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int i = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
        PN.setText(model.getValueAt(i,0).toString());
        JN.setText(model.getValueAt(i,1).toString());
        Lp.setText(model.getValueAt(i,2).toString());
        Tp.setText(model.getValueAt(i,3).toString());
        Cp.setText(model.getValueAt(i,4).toString());
        OCp.setText(model.getValueAt(i,5).toString());
        TGp.setText(model.getValueAt(i,6).toString());
        TAp.setText(model.getValueAt(i,7).toString());

    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
        Players_Info PI = new Players_Info();
        PI.setLocationRelativeTo(null);
        PI.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        getUsersList();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        PN.setText(model.getValueAt(i,0).toString());
        JN.setText(model.getValueAt(i,1).toString());
                Lp.setText("");
                Tp.setText("");
                Cp.setText("");
                OCp.setText("");
                TGp.setText("");
                TAp.setText("");
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
                JN.setText("");
                PN.setText("");
                Lp.setText("");
                Tp.setText("");
                Cp.setText("");
                OCp.setText("");
                TGp.setText("");
                TAp.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cp;
    private javax.swing.JTextField JN;
    private javax.swing.JTextField Lp;
    private javax.swing.JTextField OCp;
    private javax.swing.JTextField PN;
    private javax.swing.JTextField TAp;
    private javax.swing.JTextField TGp;
    private javax.swing.JTextField Tp;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
