package fc.splendid;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Eternity
 */
public class Players_Info extends javax.swing.JFrame {

        Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        ArrayList<user1> searchArray = new ArrayList<user1>();
    public Players_Info() {
        initComponents();
        conn=sqlconnect.connectDB();
        getUsersList();
    }
   public ArrayList<user1> getUsersList()
   {
       String sql="select * from players_info";
       ArrayList<user1> usersList = new ArrayList<user1>();
       Statement st;    
       try {
           st = conn.createStatement();
           rs = st.executeQuery(sql);

           user1 user;

           while(rs.next())
           {
               user = new user1(rs.getString("Name"),rs.getInt("JerseyNo"),rs.getString("Address"),rs.getString("Bloodgroup"),rs.getInt("PhoneNumber"),rs.getInt("Age"),rs.getFloat("Weight"),rs.getString("Position"));
               usersList.add(user);
           }
            Object [][]row = new Object[usersList.size()][8];
            String []name = {"Name","JerseyNo","Address","Bloodgroup","PhoneNumber","Age","Weight","Position"};
            Model mo;
           for(int i = 0; i<usersList.size();i++){
           row[i][0] = usersList.get(i).getname();
           row[i][1] = usersList.get(i).getjersey();
           row[i][2] = usersList.get(i).getaddress();
           row[i][3] = usersList.get(i).getbloodgroup();
           row[i][4] = usersList.get(i).getphone();
           row[i][5] = usersList.get(i).getage();
           row[i][6] = usersList.get(i).getweight();
           row[i][7] = usersList.get(i).getposition();
           }
            mo = new Model(row,name,8);
            jTable1.setModel(mo);
            jTable1.setRowHeight(40);
           
            jTable1.getColumnModel().getColumn(2);
       } 
      catch (Exception e) {
           e.printStackTrace();
       }
       return usersList;
   }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PN = new javax.swing.JTextField();
        Add = new javax.swing.JTextField();
        PH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        AGE = new javax.swing.JTextField();
        WE = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        POS = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        JN = new javax.swing.JTextField();
        BG = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 520));
        setPreferredSize(new java.awt.Dimension(1420, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UPDATE PLAYER INFORMATIONS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 204))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1420, 673));
        jPanel1.setLayout(null);

        PN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNActionPerformed(evt);
            }
        });
        jPanel1.add(PN);
        PN.setBounds(290, 50, 299, 30);

        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add);
        Add.setBounds(290, 150, 310, 40);

        PH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PHActionPerformed(evt);
            }
        });
        jPanel1.add(PH);
        PH.setBounds(290, 260, 180, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("NAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 50, 78, 31);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("ADDRESS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 150, 102, 36);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("BLOOD GROUP");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 210, 140, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("PHONE NUMBER");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 270, 160, 22);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 530, 149, 45);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setText("AGE");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 320, 138, 22);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setText("WEIGHT");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 360, 130, 40);

        AGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGEActionPerformed(evt);
            }
        });
        jPanel1.add(AGE);
        AGE.setBounds(290, 320, 58, 30);
        jPanel1.add(WE);
        WE.setBounds(290, 370, 97, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 204));
        jLabel11.setText("POSITION");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 410, 130, 40);
        jPanel1.add(POS);
        POS.setBounds(290, 420, 97, 30);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton5.setText("SAVE ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(230, 530, 149, 45);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Jersey No", "Address", "Blood Group", "Phone Number", "Age", "Weight", "Position"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(670, 40, 670, 440);

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(20, 610, 170, 50);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 204));
        jLabel12.setText("JERSEY NO");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 90, 130, 40);
        jPanel1.add(JN);
        JN.setBounds(290, 100, 97, 30);
        jPanel1.add(BG);
        BG.setBounds(290, 210, 70, 30);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 530, 150, 50);

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton7.setText("DELETE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(680, 530, 149, 45);

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton8.setText("SET PLAYERS RECORDS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(900, 530, 190, 45);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1484, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNActionPerformed

    }//GEN-LAST:event_PNActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String value1 = PN.getText();
            String value2 = JN.getText();
            String value3 = Add.getText();
            String value4 = BG.getText();
            String value5 = PH.getText();
            String value6 = AGE.getText();
            String value7 = WE.getText();
            String value8 = POS.getText();
            
            String sql= "update players_info set Name='"+value1+"',JerseyNo='"+value2+"',Address='"+value3+"',Bloodgroup='"+value4+"',PhoneNumber='"+value5+"',Age='"+value6+"',Weight='"+value7+"',Position='"+value8+" ' where JerseyNo=' " +value2+" ' ";
            pst=conn.prepareStatement(sql);
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "UPDATED");
            
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(null,E);
        }
        getUsersList();
    }//GEN-LAST:event_jButton1ActionPerformed
            
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
        AdminPage AP = new AdminPage();
        AP.setLocationRelativeTo(null);
        AP.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int i = jTable1.getSelectedRow();
         TableModel model = jTable1.getModel();
        PN.setText(model.getValueAt(i,0).toString());
        JN.setText(model.getValueAt(i,1).toString());
        Add.setText(model.getValueAt(i,2).toString());
        BG.setText(model.getValueAt(i,3).toString());
        PH.setText(model.getValueAt(i,4).toString());
        AGE.setText(model.getValueAt(i,5).toString());
        WE.setText(model.getValueAt(i,6).toString());
        POS.setText(model.getValueAt(i,7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
             PN.setText("");
             JN.setText("");
             Add.setText("");
             BG.setText("");
             PH.setText("");
             AGE.setText("");
             WE.setText("");
             POS.setText(""); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PHActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            try{    
            
            pst=conn.prepareStatement("DELETE FROM players_info where JerseyNO=?");
            pst.setString(1,JN.getText());
            pst.executeUpdate();
             
            JOptionPane.showMessageDialog(null, "DELETED");
             getUsersList();
           
    }                                        
        catch(Exception E){
         JOptionPane.showMessageDialog(null,E);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dispose();
        PlayerRecords PR = new PlayerRecords();
        PR.setLocationRelativeTo(null);
        PR.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void AGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AGEActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try{
            String query="Insert into players_info (Name,JerseyNo,Address,Bloodgroup,PhoneNumber,Age,Weight,Position) values (?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(query);

            pst.setString(1,PN.getText());

            pst.setString(2,JN.getText());

            pst.setString(3,Add.getText());

            pst.setString(4,BG.getText());
            pst.setString(5,PH.getText());
            pst.setString(6,AGE.getText());
            pst.setString(7,WE.getText());
            pst.setString(8,POS.getText());
            if(PN.getText().isEmpty()||JN.getText().isEmpty()||Add.getText().isEmpty()||BG.getText().isEmpty()||PH.getText().isEmpty()||AGE.getText().isEmpty()||WE.getText().isEmpty()||POS.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please Fill Up All the Fields");
                PN.setText("");
                JN.setText("");
                Add.setText("");
                BG.setText("");
                PH.setText("");
                AGE.setText("");
                WE.setText("");
                POS.setText("");

            } else {
                pst.execute();
                JOptionPane.showMessageDialog(null, "Saved");

                PN.setText("");
                JN.setText("");
                Add.setText("");
                BG.setText("");
                PH.setText("");
                AGE.setText("");
                WE.setText("");
                POS.setText("");

            }
        }
        catch(Exception e)
        {

            JOptionPane.showMessageDialog(null, e);
        }
        getUsersList();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Players_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Players_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Players_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Players_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Players_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AGE;
    private javax.swing.JTextField Add;
    private javax.swing.JTextField BG;
    private javax.swing.JTextField JN;
    private javax.swing.JTextField PH;
    private javax.swing.JTextField PN;
    private javax.swing.JTextField POS;
    private javax.swing.JTextField WE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
