/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fc.splendid;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Eternity
 */
public class ScoreUpdate extends javax.swing.JFrame {
         Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        ArrayList<user1> searchArray = new ArrayList<user1>();
    /**
     * Creates new form ScoreUpdate
     */
    public ScoreUpdate() {
        initComponents();
        conn=sqlconnect.connectDB();
        getUsersList();
    }
         public ArrayList<user1> getUsersList()
   {
       String sql="select * from live_score";
       ArrayList<user1> usersList = new ArrayList<user1>();
       Statement st;    
       try {
           st = conn.createStatement();
           rs = st.executeQuery(sql);

           user1 user;

           while(rs.next())
           {
               user = new user1(rs.getString("MatchVs"),rs.getInt("MatchNo"),rs.getString("Half"),rs.getInt("Minute"),rs.getString("Event"),rs.getString("Description"));
               usersList.add(user);
           }
            Object [][]row = new Object[usersList.size()][6];
            String []name = {"MatchVs","MatchNo","Half","Minute","Event","Description"};
            Model mo;
           for(int i = 0; i<usersList.size();i++){
           row[i][0] = usersList.get(i).getmatchvs();
           row[i][1] = usersList.get(i).getmatchno();
           row[i][2] = usersList.get(i).gethalf();
           row[i][3] = usersList.get(i).getminute();
           row[i][4] = usersList.get(i).getevent();
           row[i][5] = usersList.get(i).getdescription();
           
           }
            mo = new Model(row,name,6);
            jTable1.setModel(mo);
            jTable1.setRowHeight(40);
           
            jTable1.getColumnModel().getColumn(2);
       } 
      catch (Exception e) {
           e.printStackTrace();
       }
       return usersList;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        DC = new javax.swing.JTextField();
        EV = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        MV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MN = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 490));
        setPreferredSize(new java.awt.Dimension(1235, 515));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 500));
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("MINUTE");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 200, 90, 20);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "34", "35", "36", "37", "38", "39", "40", "41", "45" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(170, 200, 80, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("EVENT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 250, 60, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("DESCRIPTION");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 310, 100, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("HALF");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 160, 90, 20);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ST", "2ND" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(170, 160, 80, 20);
        jPanel1.add(DC);
        DC.setBounds(170, 300, 380, 50);
        jPanel1.add(EV);
        EV.setBounds(170, 240, 150, 30);

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(370, 380, 149, 40);

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(550, 380, 149, 40);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 380, 149, 40);

        jButton7.setBackground(new java.awt.Color(204, 255, 204));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton7.setText("RESET");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(10, 380, 170, 40);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("UPDATE SCORE");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(220, 10, 390, 42);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1300, 60);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(710, 70, 510, 402);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("MATCH VS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 80, 90, 17);
        jPanel1.add(MV);
        MV.setBounds(170, 70, 150, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("MATCH NO");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 120, 90, 17);
        jPanel1.add(MN);
        MN.setBounds(170, 110, 60, 30);

        jButton8.setBackground(new java.awt.Color(255, 102, 102));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton8.setText("BACK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(10, 430, 170, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1230, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
            String value1 = MV.getText();
            String value2 = MN.getText();
            String value3=jComboBox1.getSelectedItem().toString();
            String value4=jComboBox2.getSelectedItem().toString();
            String value5 = EV.getText();
            String value6 = DC.getText();
                        
            String sql= "update live_score set MatchVs='"+value1+"',MatchNo='"+value2+"',Half='"+value3+"',Minute='"+value4+"',Event='"+value5+"',Description='"+value6+"' where MatchNo=' " +value2+" ' ";
            pst=conn.prepareStatement(sql);
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "UPDATED");
            
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(null,E);
        }
        getUsersList();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      try{    
            
            pst=conn.prepareStatement("DELETE FROM live_score where MatchNo=?");
            pst.setString(1,MN.getText());
            pst.executeUpdate();
             
            JOptionPane.showMessageDialog(null, "DELETED");
             getUsersList();
    }                                        
        catch(Exception E){
         JOptionPane.showMessageDialog(null,E);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try{
            String query="Insert into live_score (MatchVs,MatchNo,Half,Minute,Event,Description) values (?,?,?,?,?,?)";
            pst=conn.prepareStatement(query);

            pst.setString(1,MV.getText());
            
            pst.setString(2,MN.getText());
         
            String value1=jComboBox1.getSelectedItem().toString();
            pst.setString(3,value1);
            
            String value2=jComboBox2.getSelectedItem().toString();
            pst.setString(4,value2);
            
            pst.setString(5,EV.getText());
            pst.setString(6,DC.getText());
            
           if(MV.getText().isEmpty()||MN.getText().isEmpty()||jComboBox1.getSelectedItem().toString().isEmpty()||EV.getText().isEmpty()||DC.getText().isEmpty()||jComboBox2.getSelectedItem().toString().isEmpty())
            { 
             JOptionPane.showMessageDialog(null, "Please Fill Up All the Fields");
             MV.setText("");
             MN.setText("");
             jComboBox1.setSelectedIndex(0);
             jComboBox2.setSelectedIndex(0);
             EV.setText("");
             DC.setText("");
             
            } else {
                  pst.execute();
                  JOptionPane.showMessageDialog(null, "Saved");
                  
             MV.setText("");
             MN.setText("");
             jComboBox1.setSelectedIndex(0);
             jComboBox2.setSelectedIndex(0);
             EV.setText("");
             DC.setText("");
                 
            }
            }
             catch(Exception e)
        {
            
            JOptionPane.showMessageDialog(null, e);
        } 
       getUsersList();
                         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
             MV.setText("");
             MN.setText("");
             jComboBox1.setSelectedIndex(0);
             jComboBox2.setSelectedIndex(0);
             EV.setText("");
             DC.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int i = jTable1.getSelectedRow();
         TableModel model = jTable1.getModel();
        MV.setText(model.getValueAt(i,0).toString());
        MN.setText(model.getValueAt(i,1).toString());
        String half= model.getValueAt(i,2).toString();
        if(half.equals("1ST"))
        {
            jComboBox1.setSelectedIndex(0);
        }
        else if(half.equals("2ND")){
            jComboBox1.setSelectedIndex(1);
        }
        String min= model.getValueAt(i,3).toString();
        if(min.equals("1"))
        {
            jComboBox2.setSelectedIndex(0);
        }
        else if(min.equals("2")){
            jComboBox2.setSelectedIndex(1);
        }
        else if(min.equals("3")){
            jComboBox2.setSelectedIndex(2);
        }
        else if(min.equals("4")){
            jComboBox2.setSelectedIndex(3);
        }
        else if(min.equals("5")){
            jComboBox2.setSelectedIndex(4);
        }
        else if(min.equals("6")){
            jComboBox2.setSelectedIndex(5);
        }else if(min.equals("7")){
            jComboBox2.setSelectedIndex(6);
        }else if(min.equals("8")){
            jComboBox2.setSelectedIndex(7);
        }else if(min.equals("9")){
            jComboBox2.setSelectedIndex(8);
        }else if(min.equals("10")){
            jComboBox2.setSelectedIndex(9);
        }else if(min.equals("11")){
            jComboBox2.setSelectedIndex(10);
        }else if(min.equals("12")){
            jComboBox2.setSelectedIndex(11);
        }else if(min.equals("13")){
            jComboBox2.setSelectedIndex(12);
        }else if(min.equals("14")){
            jComboBox2.setSelectedIndex(13);
        }else if(min.equals("15")){
            jComboBox2.setSelectedIndex(14);
        }else if(min.equals("16")){
            jComboBox2.setSelectedIndex(15);
        }else if(min.equals("17")){
            jComboBox2.setSelectedIndex(16);
        }else if(min.equals("18")){
            jComboBox2.setSelectedIndex(17);
        }else if(min.equals("19")){
            jComboBox2.setSelectedIndex(18);
        }else if(min.equals("20")){
            jComboBox2.setSelectedIndex(19);
        }else if(min.equals("21")){
            jComboBox2.setSelectedIndex(20);
        }else if(min.equals("22")){
            jComboBox2.setSelectedIndex(21);
        }else if(min.equals("23")){
            jComboBox2.setSelectedIndex(22);
        }else if(min.equals("24")){
            jComboBox2.setSelectedIndex(23);
        }else if(min.equals("25")){
            jComboBox2.setSelectedIndex(24);
        }else if(min.equals("26")){
            jComboBox2.setSelectedIndex(25);
        }else if(min.equals("27")){
            jComboBox2.setSelectedIndex(26);
        }else if(min.equals("28")){
            jComboBox2.setSelectedIndex(27);
        }else if(min.equals("29")){
            jComboBox2.setSelectedIndex(28);
        }else if(min.equals("30")){
            jComboBox2.setSelectedIndex(29);
        }else if(min.equals("31")){
            jComboBox2.setSelectedIndex(30);
        }else if(min.equals("32")){
            jComboBox2.setSelectedIndex(31);
        }else if(min.equals("33")){
            jComboBox2.setSelectedIndex(32);
        }else if(min.equals("34")){
            jComboBox2.setSelectedIndex(33);
        }else if(min.equals("35")){
            jComboBox2.setSelectedIndex(34);
        }else if(min.equals("36")){
            jComboBox2.setSelectedIndex(35);
        }else if(min.equals("37")){
            jComboBox2.setSelectedIndex(36);
        }else if(min.equals("38")){
            jComboBox2.setSelectedIndex(37);
        }else if(min.equals("39")){
            jComboBox2.setSelectedIndex(38);
        }else if(min.equals("40")){
            jComboBox2.setSelectedIndex(39);
        }else if(min.equals("41")){
            jComboBox2.setSelectedIndex(40);
        }else if(min.equals("42")){
            jComboBox2.setSelectedIndex(41);
        }else if(min.equals("43")){
            jComboBox2.setSelectedIndex(42);
        }else if(min.equals("44")){
            jComboBox2.setSelectedIndex(43);
        }else if(min.equals("45")){
            jComboBox2.setSelectedIndex(44);
        }
        
        EV.setText(model.getValueAt(i,4).toString());
        DC.setText(model.getValueAt(i,5).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dispose();
        AdminPage AP = new AdminPage();
        AP.setLocationRelativeTo(null);
        AP.setVisible(true);        
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DC;
    private javax.swing.JTextField EV;
    private javax.swing.JTextField MN;
    private javax.swing.JTextField MV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
