
package fc.splendid;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Eternity
 */
public class TeamRecord_Guest extends javax.swing.JFrame {

     Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;/**
     * Creates new form TeamRecord_Guest
     */
    public TeamRecord_Guest() {
        initComponents();
        conn = sqlconnect.connectDB();
        fetch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        C = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        OC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        L = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        T = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(664, 554));
        setPreferredSize(new java.awt.Dimension(670, 560));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("TEAM'S  RECORDS");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(110, 10, 360, 42);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 660, 60);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("CUP WON");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 250, 110, 30);

        C.setEditable(false);
        C.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(C);
        C.setBounds(260, 240, 90, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("OTHER CHAMPIONSHIPS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 310, 180, 30);

        OC.setEditable(false);
        OC.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(OC);
        OC.setBounds(260, 300, 90, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("LEAGUE WON");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 110, 110, 30);

        L.setEditable(false);
        L.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(L);
        L.setBounds(260, 100, 90, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("TOURNAMENTS WON");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 180, 160, 30);

        T.setEditable(false);
        T.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(T);
        T.setBounds(260, 170, 90, 40);

        jButton7.setBackground(new java.awt.Color(255, 102, 102));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(20, 430, 170, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
        TeamOverview_Guest TIG = new TeamOverview_Guest();
        TIG.setLocationRelativeTo(null);
        TIG.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed
     public void fetch()
    {      
        try{
          String League="league";
          String Tournaments="tourney";
          String Cups="cup";
          String Others="others";
          
          String sql = "select * from team_records";
          pst = conn.prepareStatement(sql);
          
          rs = pst.executeQuery();
          if(rs.next()){
             L.setText(rs.getString("league"));
             
             T.setText(rs.getString("tourney"));
             
             C.setText(rs.getString("cup"));
             
             OC.setText(rs.getString("others"));
             
          }
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(null, E);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamRecord_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamRecord_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamRecord_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamRecord_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamRecord_Guest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C;
    private javax.swing.JTextField L;
    private javax.swing.JTextField OC;
    private javax.swing.JTextField T;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
