/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fc.splendid;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class TeamOverview_Guest extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;/**
     * Creates new form TeamOverview_Guest
     */
    public TeamOverview_Guest() {
        initComponents();
        conn = sqlconnect.connectDB();
        fetch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TN = new javax.swing.JTextField();
        CN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        E = new javax.swing.JTextField();
        TP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CO = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        CH = new javax.swing.JTextField();
        C = new javax.swing.JTextField();
        M = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1420, 673));
        jPanel1.setLayout(null);

        TN.setEditable(false);
        TN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNActionPerformed(evt);
            }
        });
        jPanel1.add(TN);
        TN.setBounds(490, 100, 210, 40);

        CN.setEditable(false);
        jPanel1.add(CN);
        CN.setBounds(490, 320, 180, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("TEAM  NAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 100, 130, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("MANAGER");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 200, 102, 50);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("CHAIRMAN");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 280, 120, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("CONTACT NUMBER");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 330, 180, 22);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("ESTABLISHED");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(250, 370, 138, 22);

        jLabel10.setBackground(new java.awt.Color(204, 255, 204));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("TOTAL PLAYER");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(250, 410, 150, 40);

        E.setEditable(false);
        jPanel1.add(E);
        E.setBounds(490, 370, 90, 30);

        TP.setEditable(false);
        jPanel1.add(TP);
        TP.setBounds(490, 420, 97, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("COUNTRY");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(250, 470, 130, 40);

        CO.setEditable(false);
        jPanel1.add(CO);
        CO.setBounds(490, 470, 97, 30);

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setText("WATCH TEAM RECORDS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(600, 500, 210, 50);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("COACH");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(250, 150, 130, 40);

        CH.setEditable(false);
        jPanel1.add(CH);
        CH.setBounds(490, 270, 300, 40);

        C.setEditable(false);
        jPanel1.add(C);
        C.setBounds(490, 150, 300, 40);

        M.setEditable(false);
        jPanel1.add(M);
        M.setBounds(490, 210, 300, 40);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("CLUB DE SPLENDID");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(270, 10, 370, 42);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 960, 80);

        jButton7.setBackground(new java.awt.Color(255, 102, 102));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(10, 500, 170, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNActionPerformed

    }//GEN-LAST:event_TNActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
        TeamRecord_Guest TRG = new TeamRecord_Guest();
        TRG.setLocationRelativeTo(null);
        TRG.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
        GuestPage GP = new GuestPage();
        GP.setLocationRelativeTo(null);
        GP.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed
        public void fetch()
    {      
        try{
          String Name="team_name";
          String Coach="coach";
          String Manager="manager";
          String Chairman="chairman";
          String ContactNumber="contact_number";
          String Estd="established";
          String TotalPlayer="total_player";
          String Country="country";
          String sql = "select * from team_overview";
          pst = conn.prepareStatement(sql);
          
          rs = pst.executeQuery();
          if(rs.next()){
             TN.setText(rs.getString("team_name"));
             
             C.setText(rs.getString("coach"));
             
             M.setText(rs.getString("manager"));
             
             CH.setText(rs.getString("chairman"));
             
             CN.setText(rs.getString("contact_number"));
             
             E.setText(rs.getString("established"));
            
             TP.setText(rs.getString("total_player"));
             
             CO.setText(rs.getString("country"));
             
          }
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(null, E);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamOverview_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamOverview_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamOverview_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamOverview_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamOverview_Guest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C;
    private javax.swing.JTextField CH;
    private javax.swing.JTextField CN;
    private javax.swing.JTextField CO;
    private javax.swing.JTextField E;
    private javax.swing.JTextField M;
    private javax.swing.JTextField TN;
    private javax.swing.JTextField TP;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
