/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fc.splendid;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Eternity
 */
public class TransferPlayers extends javax.swing.JFrame {

    /**
     * Creates new form TransferPlayers
     */Connection conn=null;
     ResultSet rs=null;
     PreparedStatement pst=null;
     PreparedStatement pst1=null;
     private int sp,bp,af,tb,aa;
     double tc,bpb,afb,ta;
    public TransferPlayers() {
        initComponents();
        conn=sqlconnect.connectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PNB = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BP = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        ST = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        TA = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        AFB = new javax.swing.JTextField();
        JNB = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BF = new javax.swing.JTextField();
        BPB = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 560));
        setPreferredSize(new java.awt.Dimension(760, 580));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 560));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 560));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("TRANSFER PLAYERS");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(220, 10, 390, 42);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-2, 0, 740, 60);

        PNB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(PNB);
        PNB.setBounds(560, 110, 160, 30);

        jPanel3.setBackground(new java.awt.Color(251, 251, 251));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELLING INFOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel3.setLayout(null);

        jLabel7.setBackground(new java.awt.Color(255, 255, 51));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setText("PLAYER NAME");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 60, 120, 20);

        PN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(PN);
        PN.setBounds(210, 50, 160, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("JERSEY NO");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 110, 100, 17);

        JN.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(JN);
        JN.setBounds(210, 100, 110, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("SELLING PRICE");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 200, 130, 20);
        jPanel3.add(SP);
        SP.setBounds(210, 190, 120, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("AGENT FEE");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 280, 90, 17);
        jPanel3.add(AF);
        AF.setBounds(210, 270, 120, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("TEAM BENEFIT");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 320, 110, 17);
        jPanel3.add(TB);
        TB.setBounds(210, 310, 120, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("BUYING PRICE");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(30, 240, 130, 20);
        jPanel3.add(BP);
        BP.setBounds(210, 230, 120, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("UPDATE TABLE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(220, 380, 140, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("=");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(150, 320, 50, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 153));
        jLabel14.setText("SOLD TO");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(30, 160, 70, 17);

        ST.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(ST);
        ST.setBounds(210, 150, 110, 30);

        jButton9.setBackground(new java.awt.Color(204, 255, 204));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton9.setText("RESET");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);
        jButton9.setBounds(10, 380, 130, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(8, 70, 380, 420);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUYING INFOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel4.setLayout(null);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("UPDATE TABLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(170, 380, 150, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 153));
        jLabel12.setText("TAX");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(30, 260, 90, 17);
        jPanel4.add(TA);
        TA.setBounds(210, 250, 120, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 153));
        jLabel13.setText("TOTAL COST");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(30, 310, 90, 17);
        jPanel4.add(TC);
        TC.setBounds(210, 300, 120, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 51));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setText("PLAYER NAME");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(30, 50, 120, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("=");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(140, 310, 50, 20);
        jPanel4.add(AFB);
        AFB.setBounds(210, 210, 120, 30);

        JNB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel4.add(JNB);
        JNB.setBounds(220, 80, 110, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 153));
        jLabel15.setText("JERSEY NO");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(30, 90, 100, 17);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("AGENT FEE");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(30, 220, 90, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText(" BUYING PRICE");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(30, 180, 130, 20);
        jPanel4.add(BF);
        BF.setBounds(190, 120, 140, 30);

        BPB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel4.add(BPB);
        BPB.setBounds(190, 170, 140, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setText("BOUGHT FROM");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(30, 130, 110, 17);

        jButton8.setBackground(new java.awt.Color(204, 255, 204));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton8.setText("RESET");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);
        jButton8.setBounds(10, 380, 130, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(390, 69, 350, 420);

        jButton7.setBackground(new java.awt.Color(255, 102, 102));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(10, 500, 170, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
        AdminPage AP = new AdminPage();
        AP.setLocationRelativeTo(null);
        AP.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
            String query="Insert into transfer_sell (Name,JerseyNo,SoldTo,SellingPrice,BuyingPrice,AgentFee,TeamBenefit) values (?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(query);
            pst.setString(1,PN.getText());
            String value1=JN.getText();
            pst.setString(2,JN.getText());
            pst.setString(3,ST.getText());
            pst.setString(4,SP.getText());
            pst.setString(5,BP.getText());
            pst.setString(6,AF.getText());
            pst.setString(7,TB.getText());
                       
           if(PN.getText().isEmpty()||JN.getText().isEmpty()||ST.getText().isEmpty()||SP.getText().isEmpty()||BP.getText().isEmpty()||AF.getText().isEmpty()||TB.getText().isEmpty())
            { 
             JOptionPane.showMessageDialog(null, "Please Fill Up All the Fields");
             PN.setText("");
             JN.setText("");
             ST.setText("");
             SP.setText("");
             BP.setText("");
             AF.setText("");
             TB.setText("");
             
            } 
           else {
            pst.execute();
            pst1=conn.prepareStatement( "DELETE FROM players_info WHERE JerseyNO=?");
            pst1.setString(1,value1);
            
            pst1.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated");    
            }
            }
             catch(Exception e)
        {
            
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
             
            String value1= SP.getText();
            sp = Integer.parseInt(value1);
            
            String value2= BP.getText();
            bp = Integer.parseInt(value2);
            
            String value3= AF.getText();
            af = Integer.parseInt(value3);
            aa=(bp+af);
            tb=sp-aa;
            
            TB.setText(Integer.toString(tb));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String query="INSERT INTO transfer_buy(Name,JerseyNo,BoughtFrom,BuyingPrice,AgentFee,Tax,TotalCost) values (?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(query);
            pst.setString(1,PNB.getText());
            pst.setString(2,JNB.getText());
            pst.setString(3,BF.getText());
            pst.setString(4,BPB.getText());
            pst.setString(5,AFB.getText());
            pst.setString(6,TA.getText());
            pst.setString(7,TC.getText());
                       
           if(PNB.getText().isEmpty()||JNB.getText().isEmpty()||BF.getText().isEmpty()||BPB.getText().isEmpty()||AFB.getText().isEmpty()||TA.getText().isEmpty()||TC.getText().isEmpty())
            { 
             JOptionPane.showMessageDialog(null, "Please Fill Up All the Fields");
             PNB.setText("");
             JNB.setText("");
             BF.setText("");
             BPB.setText("");
             AFB.setText("");
             TA.setText("");
             TC.setText("");
             } 
           else {
            pst.execute();
            
            String sql="INSERT players_info(Name,JerseyNO,Address,Bloodgroup,PhoneNumber,Age,Weight,Position)values(?,?,?,?,?,?,?,?)";
            pst1=conn.prepareStatement(sql);
            pst1.setString(1,PNB.getText());
            pst1.setString(2,JNB.getText());
            
            pst1.setString(3,"NULL");
            
            pst1.setString(4,"NULL");
            pst1.setString(5,"0");
            pst1.setString(6,"0");
            pst1.setString(7,"0");
            pst1.setString(8,"NULL");
            
            pst1.execute();
            JOptionPane.showMessageDialog(null, "Updated");    
                  
                  
            }
            }
             catch(Exception e)
        {
            
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
             String value1= BPB.getText();
            bpb = Integer.parseInt(value1);
            
            String value2= AFB.getText();
            afb = Integer.parseInt(value2);
            
            String value3= TA.getText();
            ta = Double.parseDouble(value3);
            
            tc=bpb+afb+(ta/100*bpb) ;
            
            TC.setText(Double.toString(tc));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
             PNB.setText("");
             JNB.setText("");
             BF.setText("");
             BPB.setText("");
             AFB.setText("");
             TA.setText("");
             TC.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
             PN.setText("");
             JN.setText("");
             ST.setText("");
             SP.setText("");
             BP.setText("");
             AF.setText("");
             TB.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferPlayers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AF;
    private javax.swing.JTextField AFB;
    private javax.swing.JTextField BF;
    private javax.swing.JTextField BP;
    private javax.swing.JTextField BPB;
    private javax.swing.JTextField JN;
    private javax.swing.JTextField JNB;
    private javax.swing.JTextField PN;
    private javax.swing.JTextField PNB;
    private javax.swing.JTextField SP;
    private javax.swing.JTextField ST;
    private javax.swing.JTextField TA;
    private javax.swing.JTextField TB;
    private javax.swing.JTextField TC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
